### PR TITLE
Micro optimization for `#features` on ActiveRecord adapter

### PR DESCRIPTION
**Pull request by bkeepers**
I noticed `#features` was calling `Gate.all.map(&:key).to_set` to get the list of features, which will pull a lot of data over the wire to get the list of features. This replaces it with `Gate.distinct.pluck(:key).to_set`.  Thankfully, `#features` is not used in our hot code path internally (`get_all` with memoization is used when checking `#enabled?`), but this could have some impact for those with large actor sets.

```
$ ruby benchmarks/active_record_ips.rb

# Before:
            features      6.453k (± 8.3%) i/s -     32.604k in   5.088062s
# After:
            features     10.130k (± 8.6%) i/s -     50.661k in   5.038290s
```

This benchmark uses an sqlite in-memory database, so the results should be even more dramatic over a network connection.

### CODE REVIEW

**Review by jnunemaker — APPROVED** [review]
> this could have some impact for those with large actor sets.

You said Gate and actor sets a few times which confused me but I think you meant Feature and large feature sets. 

This is great! Good find.

**Comment by bkeepers** [comment]
> You said Gate and actor sets a few times which confused me but I think you meant Feature and large feature sets.

I did actually mean gates and actor sets. Since this is querying the gates table, it loads all gate data to just get the distinct feature names. So if you enable a single feature for a lot of actors, then calling `Flipper.features` will pull all the actor data over the wire just to get the feature list.

**Comment by jnunemaker** [comment]
Ok. I saw @feature_class everywhere not @gate_class so I guess I don't understand where gates were even being queried but that's ok. Regardless this is a good improvement!

**Comment by bkeepers** [comment]
🤦‍♂️ wow, I must be low on sleep or something. You’re absolutely right. I was thinking it was gates. Now I’m confused where the improvement is coming from. 

Must just be large feature sets like you said.

**Comment by jnunemaker** [comment]
🤣. I was definitely feeling crazy when you said you meant gate. Haha. 

This would definitely improve getting features as plucking a column is way faster than pulling all feature data across wire and instantiating AR objects. It's a good change especially for lots of features.

**Pull request merged**
