### PR TITLE
Deny actor gate

### LINKED ISSUE #514: Allow explicitly disabling actors
This has come up a few times. It would be great if we could come up with a good way of explicitly enabling a feature with exceptions. For example, this feature is enabled for everyone but john. Or this feature is enabled for everyone but customers on the basic tier. 

The main problem currently is that flipper is about gates and letting people through the gates. Flipper.disable is about clearing those enablements, not explicitly disabling the gate for the actor which is different. 

https://github.com/jnunemaker/flipper/issues/82#issuecomment-759626499 talks more about this. Storage of disabled is easy but the interface changes could cause quite a ripple for existing flipper users so we'd want to be careful. 

* **enable** - enables feature for gate
* **un-enable** - not disable, just removes the enabled gate if it is enabled else nothing, if actor enabled then this would remove actor, if group is enabled, it would remove group, if percentage is set it would unset it
* **disable** - disables feature for gate, disable actor would store actor id in set of disabled actors, disable group would store group in set of disabled groups, flipper feature enabled? checks would likely need throw catch or some other mechanism to explicitly say "even though this feature is enabled for this gate, it is explicitly disabled for this actor or group or other gate and should return false 

## Workarounds 

* **Create a negative feature**. If feature is :redesign, you create new feature :redesign_disabled. Each code point needs to check `Flipper.enabled?(:redesign, actor) && !Flipper.enabled?(:redesign_disabled, actor)`. A bit painful but can be wrapped up in another application method (e.g. `Redesign.enabled?(actor)` which can check both and return value). **Con**: Involves checking two features. Also involves knowing what/how the negative feature works in this context.
* **Use group + application storage**. If you have group and group checks attribute you can enable the group and have that group check an attribute on the actor. :redesign_enabled group, checks if redesign_enabled? (some attribute stored on actor). If that is false it returns false for group. If that is true it returns true for group. Then you just need to avoid using other gates. **Con**: Would break if someone fully enabled. Also involves application storage instead of all baked into flipper.
* **Use application storage + pre-feature flag check**. Check something with application logic in addition to Flipper feature check. Can also do this via Redesign.enabled?(actor) or something. That can check `return false if actor.redesign_disabled?` or whatever. **Con**: Involves you storing stuff on your own instead of baked into flipper.

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
This PR adds a new DeniedActor gate, responsible for handling the case where we want to forbid (deny!) access of an actor to the resource in question.

When calling `Flipper.deny_actor(actor)` we want to be able to deny access of an actor to a resource, overriding any permission this actor might have to see a feature. If we want to remove this, we can use the `Flipper#reinstate_actor` method.

This takes precedence over the already existing gates, so if you enable a feature to everyone (or even to a single actor), if an actor was denied, it won't have access to the feature.

Closes #514

### CODE REVIEW

**Comment by rafaeelaudibert** [comment]
@jnunemaker This is an experimental PR, and I am open to hearing your thoughts about the approach I took.

I definitely think there should be better approaches, but I didn't want to break backward compatibility, so I kept every public-facing method with the same behavior as before (except the #enabled? one, for obvious reasons), and just added some new methods on top of the already existing DSL.

Also, I read #514 and decided to go with deny/reinstate, but this is clearly open to changes.

At last, I probably didn't write enough tests or documentation, but I think this is ok for the first review.

**Comment by jnunemaker** [comment]
I'm excited to look through this but I'm on vacation this week. Just wanted you to know that's why I'll probably be slow to respond fully.

**Comment by rafaeelaudibert** [comment]
@jnunemaker No problem! I took the time in my company's Hackathon Week to do this, so I'm actually not 100% available as well, feel free to take the time you need to look at it

**Review by bkeepers — COMMENTED** [review]
Hey @rafaeelaudibert, thanks for the pull request! We've been talking for a long time about adding the ability to deny and it's something I really want.

The approach you've taken here works great for actors. I think we also need to support block/deny on boolean, groups, percentage of time, and percentage of actors. Basically, any gate should have the ability to halt.

We have talked internally about how Rules in #557 will make this easier to implement, but we don't currently have a timeline for launching rules.

I'm going to leave this open so we can keep discussing if it makes sense to go forward with adding deny support to existing gates, but just wanted to give you a heads up on our current thinking.

**Comment by rafaeelaudibert** [comment]
@bkeepers Sorry for taking this long to get back to you!

I agree with you, and I think it'd be way easier to implement this with the proposed set of rules. I'll keep this PR open just for the sake of it, in case someone wants to take my work and bring it the last mile, but I will not be able to finish it up.

Looking forward to when we have rules!

We are using Flipper in production extensively, and it's been so helpful, thank you for your product :)

**Comment by rafaeelaudibert** [comment]
I don't think this will be useful now that you've implemented expressions - great job!

I'll close this one :)

**Comment by jnunemaker** [comment]
@rafaeelaudibert I'm torn on this one. I think it is still useful to deny individual actors. 

Maybe we build a mechanism into expressions to deny. 
Or adding a `not` expression (if we don't have one, sometimes I forget or don't realize what all we support). 
Or we add a deny expression and if that matches it never checks the allow/current.

**Pull request closed without merging**
